### ISSUE TITLE
missing dsp/settings.h ?

### ISSUE THREAD

**Issue by puertassucks** [magpie240/dspman#1]
When compiling:
  - `qmake-qt5` runs fine
  - `make` gives an error:

```text
mainwindow.cpp:3:26: fatal error: dsp/settings.h: No such file or directory
```

**Comment by magpie240** [comment]
Can you pastebin (paste.kde.org) install_manifext.txt which is the build directory of DSP.

**Comment by puertassucks** [comment]
I don't have one.
